<div id="welcome">
	<div class="billing_form">
		<h2>Enter Customer Details Here</h2>
		<div class="index">Name:</div><div class="input"><input type="text" class="customer_name" /></div>
		<div class="clear"></div>
		<div class="index">Contact No.:</div><div class="input"><input type="text" class="contact_no" /></div>
		<div class="clear"></div>
		<div class="index">Address</div><div class="input"><textarea class="cust_address"></textarea></div>
		<div class="clear"></div>
		<div class="index"></div><div class="input"><input type="submit" value="Add Customer" /></div>
		<div class="clear"></div>
	</div>
</div>