<?= $this->doctype() ?>
<!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<!-- the "no-js" class is for Modernizr. -->
<head>
    <meta charset="utf-8">

    <?= $this->headTitle(); ?>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <!-- Load Styles -->
    <?php
        $this->headLink()->appendStylesheet('/css/styles.css');
        echo $this->headLink();
    ?>
    
    <!-- Load Scripts with modernizr first -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.6/css/jquery.dataTables.min.css">
    <script src='https://code.jquery.com/jquery-2.1.3.js'></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>  
    <script src="//cdn.datatables.net/1.10.6/js/jquery.dataTables.min.js"></script>


</head>
<body>
    <header>
        <div class="logo">
        Nandan's
        </div>
        <div class="navbar">
            <a class="nav_elements" href="/index">Home</a>&nbsp;<span class="divider">|</span>&nbsp;
            <a class="nav_elements" href="/billing">Billing</a>&nbsp;<span class="divider">|</span>&nbsp;
            <a class="nav_elements" id ="customer" href="/customer">Customers</a>
            <div class="hover">
                <div class="hover_element"><a href="/customer/add">Add</a></div>
                <div class="hover_element"><a href="/customer/view">View All</a></div>
            </div>
            </a>&nbsp;<span class="divider">|</span>&nbsp;
            <a class="nav_elements" href="/report">Report</a>
        </div>
    </header>
    <div id="main">
        <?php echo $this->layout()->content; ?>
    </div>
    <footer>

    </footer>

</body>
</html>
