<div id="welcome"> 
	<div class="billing_form">
		<h2>Please enter the bill details below</h2>
		<div class="index">Name:</div><div class="input"><input type="text" class="customer_name" /></div>
		<div class="clear"></div>
		<div class="index">Date:</div><div class="input"><input type="date" class="bill_date" /></div>
		<div class="clear"></div>
		<div class="index">Bill Type:</div><div class="input">
			<select class="bill_type">
				<option value=0>Select a bill type</option>
				<option value=1>Debit (Cash Received)</option>
				<option value=2>Credit (Goods Purchased)</option>
				<option value=2>Cash</option>
			</select>
		</div>
		<div class="clear"></div>
		<div class="index">Amount:</div><div class="input"><input type="number" class="amount" /></div>
		<div class="clear"></div>
		<div class="index">Description:</div><div class="input"><textarea class="desc"></textarea>
		<div class="clear"></div>
		<div class="index"></div><div class="input"><input type="submit" value="Submit" /></div>
	</div>
</div>